# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
# SPDX-License-Identifier: EUPL-1.2
---

image: git.opentalk.dev:5050/opentalk/backend/containers/rust:1.98.0-trixie

stages:
  - build
  - lint
  - test
  - trigger
  - package

variables:
  KANIKO_IMAGE: git.opentalk.dev:5050/opentalk/opentalk-devops/containers/kaniko:debug-1.25.2
  SKOPEO_IMAGE: quay.io/skopeo/stable:v1

.default_job_condition: &default_job_condition
  needs: []
  rules:
    # Run in merge requests (if there is one job with this instruction, all jobs without
    # it are ignored for the MR pipeline)
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Run on scheduled pipeline runs
    - if: $CI_PIPELINE_SOURCE == 'schedule'

include:
  - project: opentalk/ci/templates/common-lint
    ref: v1
    file: .gitlab-ci-template.yml
  - project: opentalk/ci/templates/changelog
    ref: v2
    file: .gitlab-ci-template.yml

lint:fmt:
  stage: lint
  <<: *default_job_condition
  script:
    - cargo +nightly fmt -- --check

lint:clippy:
  stage: lint
  <<: *default_job_condition
  script:
    - cargo clippy --workspace --all-features --tests -- --deny warnings

lint:doc:
  stage: lint
  <<: *default_job_condition
  variables:
    RUSTDOCFLAGS: -Dwarnings
  script: cargo doc --workspace --no-deps

lint:dependency_check:
  stage: lint
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - Cargo.lock
        - deny.toml
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - cargo-deny
      --all-features
      --workspace check
      --deny unmatched-skip
      --deny license-not-encountered
      --deny license-exception-not-encountered
      --hide-inclusion-graph

lint:unnecessary_dependencies:
  stage: lint
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script: cargo machete --with-metadata

lint:commit-signature:
  stage: lint
  needs: []
  rules:
    # Run in merge requests only.
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    # %G? will log signature information for a commit. `N` stands for "no signature", `B` for "bad signature"
    # refer to https://git-scm.com/docs/pretty-formats#Documentation/pretty-formats.txt-emGem
    # grep checks that the output does not contain any "N" or "B" characters.
    - >
      git log --format=format:'%G?' $CI_MERGE_REQUEST_DIFF_BASE_SHA..HEAD
      | grep --null-data --quiet --invert-match --regexp="N" --regexp="B"

lint:justfile:
  stage: lint
  <<: *default_job_condition
  before_script: if ! just --version; then cargo install just; fi
  script:
    # The `--fmt` command-line parameter is still unstable, but valuable anyway.
    - just --unstable --fmt --check

test:cargo_test:
  stage: test
  <<: *default_job_condition
  needs: []
  artifacts:
    reports:
      junit: target/nextest/ci/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: target/llvm-cov-target/cobertura.xml
  # this uses region for coverage summary
  coverage: /TOTAL\s+(\d+\s+)+(\d+\.\d+\%)/
  script:
    - cargo llvm-cov nextest --no-report --profile ci --workspace
    - cargo llvm-cov report --doctests --cobertura --output-path target/llvm-cov-target/cobertura.xml
    - cargo llvm-cov report --summary-only
  variables:
    RUST_LOG: retoki=trace

build:
  stage: build
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG != null
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  artifacts:
    paths:
      - target/release/retoki
    expire_in: 1 week
  script:
    - cargo auditable build --release --locked

package:read-tags:
  stage: package
  needs: []
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/ && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
  image:
    name: alpine/git
    entrypoint: ['']
  artifacts:
    reports:
      dotenv: package.env
  script:
    - git fetch --tags
    - TAGS=$(git tag --list | grep "^v[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+$" | sort -V)
    - TAGS=$(echo "$TAGS" | sort -V | head -n -1 | tr "\n" " ")
    - echo "TAGS=$TAGS" >> package.env

package:container-mr:
  stage: package
  needs:
    - build
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  image:
    name: $KANIKO_IMAGE
    pull_policy: if-not-present
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    # According to https://docs.docker.com/engine/reference/commandline/tag/
    # the tag may contain lowercase and uppercase letters, digits, underscores,
    # periods, and hyphens, so we replace everything else by '_'. It cannot start
    # with a period or hyphen, so we replace those if we find them at the start of a line.
    # It must be no longer than 128 characters, so we truncate it in addition.
    #
    # tr -c means the same as --complement, but busybox tr doesn't have that.
    #
    # Some platforms on which this service is deployed allow only 63 characters
    # for the container tag, so we restrict the length to that.
    - >
      IMAGE_TAG=$(
          echo -n "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" |
          tr -c '[:alnum:]_.-' '_' |
          sed 's/^[.-]/_/' |
          cut -c -63
      )
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Containerfile
      --destination $CI_REGISTRY_IMAGE:$IMAGE_TAG
      --force

package:container-build:
  stage: package
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image:
    name: $KANIKO_IMAGE
    pull_policy: if-not-present
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Containerfile
      --destination "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}"
      --force

package:container-create-and-push-tags:
  stage: package
  needs:
    - job: package:read-tags
      optional: true
    - job: package:container-build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image:
    name: $SKOPEO_IMAGE
    entrypoint: ['']
  script:
    - TAGS_TO_PUSH=$(./ci/create-container-tags.sh "${CI_COMMIT_TAG:-main}" "$TAGS")
    - |
      for tag in $TAGS_TO_PUSH; do
        skopeo copy \
        --src-creds="${CI_REGISTRY_USER}":"${CI_REGISTRY_PASSWORD}" \
        --dest-creds="${CI_REGISTRY_USER}":"${CI_REGISTRY_PASSWORD}" \
        "docker://${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}" "docker://${CI_REGISTRY_IMAGE}:$tag"
      done
    - echo "TAGS=$TAGS_TO_PUSH" > package.env
  artifacts:
    reports:
      dotenv: package.env
