# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
# SPDX-License-Identifier: EUPL-1.2

---

image: git.opentalk.dev:5050/opentalk/backend/containers/rust:1.84.0-bookworm

lint:fmt:
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - cargo +nightly fmt --check

lint:clippy:
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - cargo clippy -- --deny warnings

lint:licensing:
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  image:
    name: fsfe/reuse:latest
    entrypoint: ['']
  script:
    - reuse lint

lint:dependency_check:
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - Cargo.lock
        - deny.toml
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - cargo-deny
      --workspace
      check
      --deny unmatched-skip
      --deny license-not-encountered
      --deny license-exception-not-encountered

lint:yaml:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  image: alpine:3.21
  before_script:
    - apk add --no-cache yamllint
  script: yamllint .

lint:toml:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script: taplo fmt --check

lint:commit:
  image: node:lts-alpine
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache git
    - npm install -g @commitlint/cli @commitlint/config-conventional
  script:
    - npx commitlint --from $CI_MERGE_REQUEST_DIFF_BASE_SHA --to HEAD --verbose

lint:trigger_changelog_preview:
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    PIPELINE_PROJECT_PATH: $CI_PROJECT_PATH
    PIPELINE_MERGE_REQUEST_PROJECT_PATH: $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH
    PIPELINE_MERGE_REQUEST_SOURCE_BRANCH_NAME: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    PIPELINE_MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
  trigger: opentalk/tools/check-changelog

test:cargo_test:
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  artifacts:
    paths:
      - target/coverage/html
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/coverage/cobertura.xml
  coverage: '/Coverage: \d+(?:\.\d+)?/'
  variables:
    # Used for coverage
    COVERAGE_XML_PATH: 'concat("Coverage: ", 100 * string(//coverage/@line-rate), "%")'
  before_script:
    - rustup component add rustfmt llvm-tools-preview
    # libxml2-utils contains the xmllint command used below
    - apt-get update && apt-get install -y libxml2-utils
  script:
    - RUSTFLAGS="-C instrument-coverage -C link-arg=-fuse-ld=lld"
      LLVM_PROFILE_FILE="$(pwd)/target/coverage/raw/coverage-%p-%m.profraw"
      cargo test --locked

    # Extract code coverage data
    - grcov target/coverage/raw
      --binary-path ./target/debug/
      --source-dir .
      --output-types cobertura,html
      --branch
      --ignore-not-existing
      --ignore "*cargo*"
      --output-path target/coverage

    # Print out the coverage percentage for GitLab
    - xmllint --xpath "$COVERAGE_XML_PATH" target/coverage/cobertura.xml

build:
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG != null
  artifacts:
    paths:
      - target/release/retoki
    expire_in: 1 week
  script:
    - cargo auditable build --release --locked --workspace

package:container:
  needs:
    - build
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG != null
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - |
      /kaniko/executor \
        --registry-mirror mirror.gcr.io \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/ci/Dockerfile \
        --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH \
        --force
    - |
      if [ "$CI_COMMIT_TAG" != "" ]; then
        /kaniko/executor \
          --registry-mirror mirror.gcr.io \
          --context $CI_PROJECT_DIR \
          --dockerfile $CI_PROJECT_DIR/ci/Dockerfile \
          --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG \
          --force;
      fi
