# SPDX-FileCopyrightText: OpenTalk Team <mail@opentalk.eu>
# SPDX-License-Identifier: EUPL-1.2

[package]
edition = "2021"
license = "EUPL-1.2"
name = "relbo"
version = "0.1.0"

[dependencies]
clap = { version = "4.5.13", features = ["derive", "env"] }
derive_builder = "0.20.0"
figment = { version = "0.10.19", features = ["env", "toml"] }
gitlab = "0.1709.0"
http = "1.1.0"
itertools = "0.14.0"
jiff = { version = "0.2.0", features = ["serde"] }
owo-colors = "4.0.0"
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }
snafu = "0.8.4"
url = { version = "2.5.2", features = ["serde"] }
urlencoding = "2"

[dev-dependencies]
derive_more = { version = "2.0.0", features = [
  "as_ref",
  "deref",
  "display",
  "into",
] }
mockall = "0.13.0"
pretty_assertions = "1.4.0"
strip-ansi-escapes = "0.2.0"
