# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
# SPDX-License-Identifier: EUPL-1.2

[package]
description = "release toolkit - tools for bundling product releases"
edition = "2024"
license = "EUPL-1.2"
name = "retoki"
version = "0.11.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive", "env"] }
derive_more = { version = "2.0.0", features = ["display", "from", "into"] }
gitlab = "0.1804.0"
indexmap = { version = "2.2.6", features = ["serde"] }
indicatif = { version = "0.18.0", features = ["rayon"] }
owo-colors = "4.0.0"
rayon = "1.10.0"
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = { version = "1.0.118" }
serde_yaml = "0.9.34"
tabled = "0.20.0"
tera = "1.20.0"
time = { version = "0.3.36", features = [
  "macros",
  "serde",
  "serde-human-readable",
  "serde-well-known",
] }
url = "2.5.2"

[dev-dependencies]
insta = { version = "1.40.0", features = ["glob", "yaml"] }
tempfile = "3.12.0"
