# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
# SPDX-License-Identifier: EUPL-1.2

SPDX-PackageDownloadLocation = "https://git.opentalk.dev/opentalk/tools/retoki"
SPDX-PackageName = "retoki"
SPDX-PackageSupplier = "OpenTalk GmbH <mail@opentalk.eu>"
version = 1

[[annotations]]
SPDX-FileCopyrightText = "OpenTalk GmbH <mail@opentalk.eu>"
SPDX-License-Identifier = "EUPL-1.2"
path = [
  ".commitlintrc.json",
  "CHANGELOG.md",
  "Cargo.lock",
  "README.md",
  "renovate.json",
  "src/bot_templates/**.md",
  "src/snapshots/**.snap",
  "templates/**.md",
  "tests/**/snapshots/**.snap",
  "tests/README.md",
]
precedence = "aggregate"
