# SPDX-FileCopyrightText: OpenTalk Team <mail@opentalk.eu>
# SPDX-License-Identifier: EUPL-1.2

SPDX-PackageDownloadLocation = "https://git.opentalk.dev/opentalk/tools/relbo"
SPDX-PackageName = "relbo"
SPDX-PackageSupplier = "OpenTalk Team <mail@opentalk.eu>"
version = 1

[[annotations]]
SPDX-FileCopyrightText = "OpenTalk Team <mail@opentalk.eu>"
SPDX-License-Identifier = "EUPL-1.2"
path = ["Cargo.lock", "renovate.json", "src/snapshots/**", "src/templates/**"]
precedence = "aggregate"
