# SPDX-License-Identifier: EUPL-1.2
# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>

[profile.default]
default-filter = 'all()'

[profile.ci]
default-filter = 'all()'

[profile.ci.junit]
path = "junit.xml"
